In [74]:
from mxnet import np, npx, autograd, initializer
from mxnet.gluon import nn, Trainer
from d2l import mxnet as d2l
from pdb import set_trace
npx.set_np()

In [119]:
npx.num_gpus()

0

In [70]:
X = np.random.uniform(size=(10000, 5))

In [71]:
net = nn.Sequential()
net.add(nn.Dense(10, activation='relu'))
net.add(nn.Dense(2))
net.initialize(initializer.Normal(sigma=0.01))
net[0].initialize(initializer.Constant(42), force_reinit=True)
net(X);

In [72]:
net[0].bias.data()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
net[0].weight.data(ctx=X.ctx)

array([[42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.]])

In [110]:
class TensorReduction(nn.Block):
    def __init__(self, i, k, **kwargs):
        super().__init__(**kwargs)
        self.weight = self.params.get('weight', shape=(i, i, k))
    def forward(self, x):
        reduction = np.sum(np.dot(x, x.T)[:, :, np.newaxis]*self.weight.data(ctx=x.ctx), axis=(0, 1))
        return reduction

In [111]:
tr = TensorReduction(5, 6)
tr.initialize()

In [105]:
np.dot(x, x.T).shape

(5, 5)

In [112]:
tr(x)

array([ 4.5478538e-01,  2.5258830e-01, -2.9252496e-01, -3.2406211e-02,
        2.1053758e-04, -8.4842220e-02])

In [67]:
x = np.random.normal(size=(5, 1))

In [62]:
x

array([[-0.21280758],
       [-1.0651625 ],
       [ 0.58222646],
       [ 1.3171352 ]])

In [61]:
x.transpose()

array([[-0.21280758, -1.0651625 ,  0.58222646,  1.3171352 ]])

In [63]:
np.dot(x, x.transpose())

array([[ 0.04528707,  0.22667466, -0.1239022 , -0.28029636],
       [ 0.22667466,  1.1345712 , -0.6201658 , -1.402963  ],
       [-0.1239022 , -0.6201658 ,  0.33898765,  0.766871  ],
       [-0.28029636, -1.402963  ,  0.766871  ,  1.7348452 ]])

In [51]:
tr.weight.data()

array([[[-0.03592555,  0.02544872, -0.06961475, -0.06309703,
         -0.06252202],
        [ 0.00786804,  0.03669995, -0.01432895,  0.06448459,
          0.01634079],
        [ 0.02242811, -0.06052826, -0.03381333,  0.015409  ,
          0.03993514],
        [ 0.0545066 , -0.06752646, -0.00190943, -0.02182666,
         -0.02257175],
        [ 0.02982339,  0.02601493,  0.0281469 ,  0.06092948,
          0.05233438]],

       [[ 0.02933844,  0.02538025,  0.06228914,  0.06553596,
          0.00526186],
        [-0.05702699, -0.05396048, -0.03316882,  0.00072701,
         -0.02750293],
        [-0.0220647 ,  0.03229611, -0.05007299, -0.00172585,
          0.04535381],
        [-0.04338929,  0.06644533,  0.0575491 ,  0.00613707,
         -0.05498286],
        [-0.01889331, -0.05184583, -0.05523539,  0.0671192 ,
          0.01409542]],

       [[ 0.04929065,  0.04462399,  0.02394763, -0.05812056,
          0.04590692],
        [-0.06211501, -0.06007318, -0.03704158,  0.06180675,
          0